# Serverless Schema - https://www.serverless.com/framework/docs/providers/aws/guide/serverless.yml
# See - https://github.com/serverless/serverless/blob/v2/docs/providers/aws/guide/functions.md

service: function-gc-active-conversations-action-nodejs

frameworkVersion: '3'

configValidationMode: warn

custom:
  awsRegion: us-east-1
  logLevel: DEBUG

provider:
  name: aws
  deploymentBucket:
    name: 'serverless-local-deploys'
    maxPreviousDeploymentArtifacts: 10
  versionFunctions: false
  logRetentionInDays: 7
  region: '${self:custom.awsRegion}'

## Define all Functions and Resources in-line
functions:
  echo:
    handler: src/index.handler
    name: function-gc-active-conversations-action-nodejs
    description: Genesys Cloud Function to get active conversations for user
    ## Runtime may be deprecated and need to be updated when using the example.
    runtime: nodejs20.x
    memorySize: 512
    timeout: 15
    architecture: arm64
    tracing: PassThrough # optional, overwrite, can be 'Active' or 'PassThrough'
    environment:
      LogLevel: ${self:custom.logLevel}
